org: nelsoncode019
app: aws-python-http-api
service: aws-python-http-api
frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.8

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get

plugins:
  - serverless-offline
  - serverless-python-requirements
